# Generated by Django 5.0.3 on 2025-02-03 06:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0003_alter_department_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='archive',
            field=models.BooleanField(default=False, help_text='Is archived'),
        ),
        migrations.AddField(
            model_name='employee',
            name='end_date',
            field=models.DateField(blank=True, help_text='Fired date', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='start_date',
            field=models.DateField(default=datetime.date.today, help_text='Work till', null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(help_text='Full name', max_length=150),
        ),
    ]
