# Generated by Django 5.0.4 on 2025-07-29 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0009_rename_modified_time_department_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 29, 21, 10, 39, 844995), editable=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 29, 21, 10, 39, 844995), editable=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 29, 21, 10, 39, 844995), editable=False),
        ),
    ]
