# Generated by Django 5.0.3 on 2025-08-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0024_alter_department_created_alter_employee_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
