# Generated by Django 4.2.23 on 2025-10-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0029_alter_employee_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='department',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='archive',
            field=models.BooleanField(db_index=True, default=False, help_text='Is archived'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='archive',
            field=models.BooleanField(db_index=True, default=False, help_text='Is archived'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='organization',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=150),
        ),
    ]
