# Generated by Django 5.0.3 on 2024-09-03 10:17

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('res', '0005_resource_accounts_provider_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessProfile',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=9)),
                ('name', models.CharField(blank=True, max_length=32)),
                ('delete_mark', models.BooleanField(default=False)),
                ('create_date', models.DateField(default=datetime.date.today, help_text='Create date', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Expiry date', null=True)),
                ('archive', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True)),
                ('help_text', models.TextField(blank=True)),
                ('resource', models.ForeignKey(help_text='Resource', on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='res.resource')),
            ],
            options={
                'verbose_name': 'Access Profile',
            },
        ),
    ]
