# Generated by Django 5.0.3 on 2024-09-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0006_alter_accessprofile_groups'),
        ('res', '0005_resource_accounts_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessprofile',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Profile groups', related_name='profiles', to='res.resourcegroup'),
        ),
        migrations.DeleteModel(
            name='ResourceGroup',
        ),
    ]
