# Generated by Django 5.0.4 on 2025-07-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0008_accessprofile_modified_time_account_modified_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessprofile',
            name='modified_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='modified_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
