# Generated by Django 4.2.23 on 2025-10-11 08:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonCounter',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('table_name', models.CharField(max_length=50)),
                ('prefix', models.CharField(blank=True, default='', max_length=5)),
                ('counter', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Counter for model',
            },
        ),
    ]
