# Generated by Django 5.0.4 on 2024-06-05 19:53

import datetime
import django.db.models.deletion
import macaddress.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=9)),
                ('name', models.CharField(blank=True, max_length=32)),
                ('delete_mark', models.BooleanField(default=False)),
                ('virtual', models.BooleanField(default=False)),
                ('has_interfaces', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Equipment type',
            },
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=9)),
                ('delete_mark', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('mac', macaddress.fields.MACAddressField(blank=True, integer=True, null=True)),
                ('archive', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True)),
                ('virtual', models.BooleanField(default=False)),
                ('ipv4_address', models.GenericIPAddressField(blank=True, null=True)),
                ('ipv4_gateway', models.GenericIPAddressField(blank=True, null=True)),
                ('ipv4_network_mask', models.IntegerField(default=0)),
                ('dns', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Interface',
                'ordering': ['title', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InterfaceType',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=9)),
                ('name', models.CharField(blank=True, max_length=32)),
                ('delete_mark', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Interface Type',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=9)),
                ('delete_mark', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('archive', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Service',
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=9)),
                ('name', models.CharField(blank=True, max_length=32)),
                ('delete_mark', models.BooleanField(default=False)),
                ('archive', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Software',
            },
        ),
        migrations.CreateModel(
            name='SoftwareVersion',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=9)),
                ('name', models.CharField(blank=True, max_length=32)),
                ('delete_mark', models.BooleanField(default=False)),
                ('archive', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True)),
                ('release_date', models.DateField(default=datetime.date.today, null=True)),
            ],
            options={
                'verbose_name': 'Software Version',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=9)),
                ('delete_mark', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('archive', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Supplier',
                'ordering': ['name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentModel',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=9)),
                ('delete_mark', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(blank=True, help_text='Full title for printing', max_length=150)),
                ('model_number', models.CharField(blank=True, max_length=50)),
                ('info_page_url', models.URLField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('equipment_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='models', to='equipment.equipmenttype')),
            ],
            options={
                'verbose_name': 'Equipment model',
                'ordering': ['name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=9)),
                ('delete_mark', models.BooleanField(default=False)),
                ('is_group', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(blank=True, help_text='Full title for printing', max_length=150)),
                ('image', models.ImageField(blank=True, upload_to='equipment/')),
                ('serial_number', models.CharField(blank=True, max_length=150)),
                ('virtual', models.BooleanField(default=False)),
                ('has_interfaces', models.BooleanField(default=False)),
                ('start_date', models.DateField(default=datetime.date.today, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('archive', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('hostname', models.CharField(blank=True, max_length=50)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='org.employee')),
                ('parent', models.ForeignKey(blank=True, limit_choices_to={'is_group': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='equipment.equipment')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipments', to='equipment.equipmentmodel')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipments', to='equipment.equipmenttype')),
            ],
            options={
                'verbose_name': 'Equipment',
                'ordering': ['title', 'name', 'code'],
            },
        ),
    ]
