# Generated by Django 5.0.4 on 2024-05-12 07:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='id',
        ),
        migrations.AddField(
            model_name='service',
            name='code',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='service',
            name='delete_mark',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='service',
            name='name',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
