# Generated by Django 5.0.4 on 2024-05-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_alter_service_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
    ]
