# Generated by Django 5.0.3 on 2025-04-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_equipment_is_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='equip_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
