# Generated by Django 5.0.4 on 2024-05-12 10:03

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_service_is_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=9)),
                ('name', models.CharField(blank=True, max_length=32)),
                ('delete_mark', models.BooleanField(default=False)),
                ('archive', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Software',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='equipment.equipment'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SoftwareVersion',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=9)),
                ('name', models.CharField(blank=True, max_length=32)),
                ('delete_mark', models.BooleanField(default=False)),
                ('archive', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True)),
                ('release_date', models.DateField(default=datetime.date.today, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='equipment.software')),
            ],
            options={
                'verbose_name': 'Software Version',
            },
        ),
    ]
