# Generated by Django 5.0.4 on 2024-05-12 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_software_service_archive_service_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='software',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='equipment.software'),
        ),
        migrations.AddField(
            model_name='service',
            name='software_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='equipment.softwareversion'),
        ),
        migrations.AlterField(
            model_name='service',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'archive': False, 'delete_mark': False}, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='equipment.equipment'),
        ),
    ]
