# Generated by Django 5.0.4 on 2024-05-12 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_alter_service_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='owner',
            new_name='equipment',
        ),
    ]
