# Generated by Django 5.0.4 on 2024-05-12 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0008_rename_owner_service_equipment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='softwareversion',
            old_name='owner',
            new_name='software',
        ),
    ]
