# Generated by Django 5.0.4 on 2024-05-12 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0009_rename_owner_softwareversion_software'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interface',
            old_name='owner',
            new_name='equipment',
        ),
    ]
