# Generated by Django 5.0.4 on 2025-04-21 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_alter_equipment_model'),
        ('equipment', '0009_alter_equipment_name'),
    ]

    operations = [
    ]
