# Generated by Django 5.0.4 on 2024-05-12 10:42

import macaddress.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0010_rename_owner_interface_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='mac',
            field=macaddress.fields.MACAddressField(blank=True, integer=True),
        ),
    ]
