# Generated by Django 5.0.4 on 2024-05-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0011_alter_interface_mac'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='virtual',
            field=models.BooleanField(default=False),
        ),
    ]
