# Generated by Django 5.0.4 on 2024-05-13 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0012_interface_virtual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='equipment.service'),
        ),
    ]
