# Generated by Django 5.0.4 on 2025-07-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0012_equipment_modified_time_equipmentmodel_modified_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='modified_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='equipmentmodel',
            name='modified_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='modified_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='interface',
            name='modified_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='interfacetype',
            name='modified_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='modified_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='modified_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='softwareversion',
            name='modified_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='modified_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
