# Generated by Django 5.0.3 on 2024-05-14 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0015_service_organization'),
        ('org', '0006_alter_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='org.organization'),
        ),
        migrations.AlterField(
            model_name='service',
            name='software_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='equipment.softwareversion'),
        ),
    ]
