# Generated by Django 5.0.4 on 2025-07-29 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0015_rename_modified_time_equipment_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 29, 21, 10, 39, 844995), editable=False),
        ),
        migrations.AddField(
            model_name='equipmentmodel',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 29, 21, 10, 39, 844995), editable=False),
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 29, 21, 10, 39, 844995), editable=False),
        ),
        migrations.AddField(
            model_name='interface',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 29, 21, 10, 39, 844995), editable=False),
        ),
        migrations.AddField(
            model_name='interfacetype',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 29, 21, 10, 39, 844995), editable=False),
        ),
        migrations.AddField(
            model_name='service',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 29, 21, 10, 39, 844995), editable=False),
        ),
        migrations.AddField(
            model_name='software',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 29, 21, 10, 39, 844995), editable=False),
        ),
        migrations.AddField(
            model_name='softwareversion',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 29, 21, 10, 39, 844995), editable=False),
        ),
        migrations.AddField(
            model_name='supplier',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 29, 21, 10, 39, 844995), editable=False),
        ),
    ]
