# Generated by Django 5.0.3 on 2024-05-14 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0016_alter_service_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='software',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='equipment.software'),
        ),
    ]
