# Generated by Django 5.0.4 on 2025-07-29 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0016_equipment_created_equipmentmodel_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 29, 21, 48, 6, 686266), editable=False),
        ),
        migrations.AlterField(
            model_name='equipmentmodel',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 29, 21, 48, 6, 686266), editable=False),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 29, 21, 48, 6, 686266), editable=False),
        ),
        migrations.AlterField(
            model_name='interface',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 29, 21, 48, 6, 686266), editable=False),
        ),
        migrations.AlterField(
            model_name='interfacetype',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 29, 21, 48, 6, 686266), editable=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 29, 21, 48, 6, 686266), editable=False),
        ),
        migrations.AlterField(
            model_name='software',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 29, 21, 48, 6, 686266), editable=False),
        ),
        migrations.AlterField(
            model_name='softwareversion',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 29, 21, 48, 6, 686266), editable=False),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 29, 21, 48, 6, 686266), editable=False),
        ),
    ]
