# Generated by Django 5.0.3 on 2024-05-15 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0017_alter_service_software'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='is_group',
        ),
        migrations.AlterField(
            model_name='service',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='equipment.service'),
        ),
    ]
