# Generated by Django 5.0.4 on 2024-05-16 17:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0019_interface_dns_interface_ipv4_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterfaceType',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=9)),
                ('name', models.CharField(blank=True, max_length=32)),
                ('delete_mark', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Interface Type',
            },
        ),
        migrations.AddField(
            model_name='interface',
            name='interface_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='equipment.interfacetype'),
            preserve_default=False,
        ),
    ]
