# Generated by Django 5.0.4 on 2024-05-21 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0020_interfacetype_interface_interface_type'),
        ('res', '0009_resource_admin_page_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='connected_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'resource_type.category': 'network'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='res.resource'),
        ),
    ]
