# Generated by Django 5.0.4 on 2024-05-22 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0021_interface_connected_to'),
        ('res', '0010_resource_resource_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='connected_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'resource_type__category': 'network'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='res.resource'),
        ),
    ]
