# Generated by Django 5.0.4 on 2024-05-25 09:17

import macaddress.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0023_alter_interface_connected_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='mac',
            field=macaddress.fields.MACAddressField(blank=True, integer=True, null=True),
        ),
    ]
