# Generated by Django 5.0.4 on 2024-05-26 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0024_alter_interface_mac'),
        ('org', '0007_employee_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='org.employee'),
        ),
    ]
