# Generated by Django 5.0.3 on 2025-07-31 05:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0028_alter_equipment_created_alter_equipmentmodel_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 31, 5, 47, 14, 489809, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='equipmentmodel',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 31, 5, 47, 14, 489809, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 31, 5, 47, 14, 489809, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='interface',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 31, 5, 47, 14, 489809, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='interfacetype',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 31, 5, 47, 14, 489809, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 31, 5, 47, 14, 489809, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='software',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 31, 5, 47, 14, 489809, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='softwareversion',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 31, 5, 47, 14, 489809, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 31, 5, 47, 14, 489809, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
