# Generated by Django 5.0.4 on 2025-08-17 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0034_alter_equipment_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_folder': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='equipment.equipment'),
        ),
    ]
