# Generated by Django 5.0.4 on 2025-08-17 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0035_alter_equipment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='software_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='equipment.softwareversion'),
        ),
    ]
