# Generated by Django 4.2.23 on 2025-10-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0036_alter_service_software_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='archive',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='equipmentmodel',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='equipmentmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='equipmentmodel',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='interface',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='interface',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='interface',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='interfacetype',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='interfacetype',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='interfacetype',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='interfacetype',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='service',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='service',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='archive',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='software',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='software',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='softwareversion',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='softwareversion',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='softwareversion',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='softwareversion',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
