# Generated by Django 4.2.23 on 2025-10-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0037_alter_equipment_archive_alter_equipment_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='delete_mark',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='equipmentmodel',
            name='delete_mark',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='delete_mark',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='interface',
            name='delete_mark',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='interfacetype',
            name='delete_mark',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='delete_mark',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='software',
            name='delete_mark',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='softwareversion',
            name='delete_mark',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='delete_mark',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
