# Generated by Django 5.0.3 on 2024-06-19 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0003_resourcegroup_archive_resourcegroup_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcegroup',
            name='name',
            field=models.CharField(help_text='Name', max_length=150),
        ),
    ]
