# Generated by Django 5.0.3 on 2024-09-03 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0004_alter_resourcegroup_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='accounts_provider',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='resource',
            name='accounts_from',
            field=models.ForeignKey(blank=True, limit_choices_to={'accounts_provider': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='res.resource'),
        ),
    ]
