# Generated by Django 5.0.3 on 2025-06-24 12:38

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0006_alter_resourcegroup_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='resource_category', chained_model_field='category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='res.resourcetype'),
        ),
    ]
