# Generated by Django 5.0.4 on 2025-07-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0010_alter_resource_modified_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='modified_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='resourcegroup',
            name='modified_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='resourcetype',
            name='modified_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
