# Generated by Django 5.0.4 on 2025-07-07 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0011_alter_resource_modified_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='modified_time',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='resourcegroup',
            old_name='modified_time',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='resourcetype',
            old_name='modified_time',
            new_name='modified',
        ),
    ]
