# Generated by Django 5.0.3 on 2025-07-31 05:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0025_alter_resource_created_alter_resourcegroup_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 31, 5, 47, 14, 489809, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='resourcegroup',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 31, 5, 47, 14, 489809, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='resourcetype',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 31, 5, 47, 14, 489809, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
