# Generated by Django 4.2.23 on 2025-10-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0029_alter_resource_resource_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='archive',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='resource',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='resource',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='resourcegroup',
            name='archive',
            field=models.BooleanField(db_index=True, default=False, help_text='Is archived'),
        ),
        migrations.AlterField(
            model_name='resourcegroup',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='resourcegroup',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='resourcegroup',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='resourcegroup',
            name='name',
            field=models.CharField(db_index=True, help_text='Name', max_length=150),
        ),
        migrations.AlterField(
            model_name='resourcetype',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='resourcetype',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='resourcetype',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='resourcetype',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
    ]
