# Generated by Django 4.2.23 on 2025-10-11 20:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('code', models.CharField(blank=True, db_index=True, max_length=9)),
                ('delete_mark', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(blank=True, help_text='Operation name', max_length=150, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Operation description', verbose_name='Description')),
                ('archive', models.BooleanField(db_index=True, default=False, help_text='Mark operation as archived', verbose_name='Archive')),
                ('comment', models.TextField(blank=True, help_text='Additional comments', verbose_name='Comment')),
            ],
            options={
                'verbose_name': 'Operation',
                'verbose_name_plural': 'Operations',
                'ordering': ['name', 'code'],
                'indexes': [models.Index(fields=['name'], name='operation_name'), models.Index(fields=['archive'], name='operation_archive')],
            },
        ),
    ]
