# Generated by Django 5.2.7 on 2025-10-15 06:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0002_initial'),
        ('res', '0001_initial'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRType',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('code', models.CharField(blank=True, db_index=True, max_length=9)),
                ('name', models.CharField(blank=True, db_index=True, max_length=32)),
                ('delete_mark', models.BooleanField(db_index=True, default=False)),
                ('url_root', models.URLField()),
                ('archive', models.BooleanField(db_index=True, default=False)),
                ('fixed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'QR Type',
            },
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('code', models.CharField(blank=True, db_index=True, max_length=9)),
                ('name', models.CharField(blank=True, db_index=True, max_length=32)),
                ('delete_mark', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('archive', models.BooleanField(db_index=True, default=False)),
                ('fixed', models.BooleanField(default=False)),
                ('guid_public_code', models.UUIDField(default=uuid.uuid4)),
                ('short_public_code', models.CharField(blank=True, max_length=50)),
                ('url', models.CharField(blank=True, max_length=150)),
                ('operation', models.CharField(blank=True, max_length=150)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('equipment', models.ForeignKey(blank=True, help_text='Linked Equipment object', limit_choices_to={'archive': False, 'delete_mark': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='equipment.equipment')),
                ('operations', models.ManyToManyField(blank=True, help_text='Operations associated with this QR code', related_name='qr_codes_operations', to='service.operation', verbose_name='Operations')),
                ('resource', models.ForeignKey(blank=True, help_text='Linked Resource object', limit_choices_to={'archive': False, 'delete_mark': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='res.resource')),
                ('service', models.ForeignKey(blank=True, help_text='Linked Service object', limit_choices_to={'archive': False, 'delete_mark': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='equipment.service')),
                ('qr_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qr.qrtype')),
            ],
            options={
                'verbose_name': 'QR Code',
                'indexes': [models.Index(fields=['short_public_code'], name='short_public_code'), models.Index(fields=['equipment'], name='qrcode_equipment'), models.Index(fields=['resource'], name='qrcode_resource'), models.Index(fields=['service'], name='qrcode_service')],
            },
        ),
    ]
