# Generated by Django 5.0.4 on 2024-06-05 19:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QRType',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=9)),
                ('name', models.CharField(blank=True, max_length=32)),
                ('delete_mark', models.BooleanField(default=False)),
                ('url_root', models.URLField()),
                ('archive', models.BooleanField(default=False)),
                ('fixed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'QR Type',
            },
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=9)),
                ('name', models.CharField(blank=True, max_length=32)),
                ('delete_mark', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('archive', models.BooleanField(default=False)),
                ('fixed', models.BooleanField(default=False)),
                ('qr_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qr.qrtype')),
            ],
            options={
                'verbose_name': 'QR Code',
            },
        ),
    ]
