# Generated by Django 5.0.4 on 2024-05-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrtype',
            name='fixed',
            field=models.BooleanField(default=False),
        ),
    ]
