# Generated by Django 5.0.3 on 2025-07-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0002_qrcode_guid_public_code_qrcode_short_public_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='url',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
