# Generated by Django 5.0.4 on 2025-07-03 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0003_qrcode_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='modified_time',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AddField(
            model_name='qrtype',
            name='modified_time',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
