# Generated by Django 5.0.4 on 2025-07-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0004_qrcode_modified_time_qrtype_modified_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='modified_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='qrtype',
            name='modified_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
