# Generated by Django 5.0.4 on 2025-07-29 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0012_alter_qrcode_created_alter_qrtype_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 29, 21, 54, 15, 734228), editable=False),
        ),
        migrations.AlterField(
            model_name='qrtype',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 29, 21, 54, 15, 734228), editable=False),
        ),
    ]
