# Generated by Django 5.0.3 on 2025-07-31 05:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0022_alter_qrcode_created_alter_qrtype_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 31, 5, 47, 14, 489809, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='qrtype',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 31, 5, 47, 14, 489809, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
