# Generated by Django 5.0.3 on 2025-08-01 11:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0023_alter_qrcode_created_alter_qrtype_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='qrtype',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
