# Generated by Django 4.2.23 on 2025-10-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0027_alter_qrcode_delete_mark_alter_qrtype_delete_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
