# Generated by Django 5.2.7 on 2025-10-11 18:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0038_alter_equipment_delete_mark_and_more'),
        ('qr', '0028_qrcode_qr_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRServiceLink',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('code', models.CharField(blank=True, db_index=True, max_length=9)),
                ('name', models.CharField(blank=True, db_index=True, max_length=32)),
                ('delete_mark', models.BooleanField(db_index=True, default=False)),
                ('link_type', models.CharField(choices=[('equipment', 'Equipment'), ('service', 'Service')], help_text='Type of linked object', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Description of the link')),
                ('is_primary', models.BooleanField(default=False, help_text='Primary link for this QR code')),
                ('archive', models.BooleanField(db_index=True, default=False)),
                ('equipment', models.ForeignKey(blank=True, help_text='Linked Equipment object', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_links', to='equipment.equipment')),
                ('qr_code', models.ForeignKey(help_text='QR Code to link', on_delete=django.db.models.deletion.CASCADE, related_name='service_links', to='qr.qrcode')),
                ('service', models.ForeignKey(blank=True, help_text='Linked Service object', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_links', to='equipment.service')),
            ],
            options={
                'verbose_name': 'QR Service Link',
                'verbose_name_plural': 'QR Service Links',
                'indexes': [models.Index(fields=['qr_code', 'link_type'], name='qr_service_link_type'), models.Index(fields=['equipment'], name='qr_service_link_equipment'), models.Index(fields=['service'], name='qr_service_link_service'), models.Index(fields=['is_primary'], name='qr_service_link_primary')],
                'unique_together': {('qr_code', 'equipment'), ('qr_code', 'service')},
            },
        ),
    ]
