# Generated by Django 5.2.7 on 2025-10-11 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0029_qrservicelink'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='qrservicelink',
            unique_together=set(),
        ),
    ]
