# Generated by Django 4.2.23 on 2025-10-11 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0030_alter_qrservicelink_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QRServiceLink',
        ),
    ]
