# Generated by Django 4.2.23 on 2025-10-11 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0038_alter_equipment_delete_mark_and_more'),
        ('res', '0031_alter_resource_delete_mark_and_more'),
        ('qr', '0031_delete_qrservicelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='equipment',
            field=models.ForeignKey(blank=True, help_text='Linked Equipment object', limit_choices_to={'archive': False, 'delete_mark': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='equipment.equipment'),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='resource',
            field=models.ForeignKey(blank=True, help_text='Linked Resource object', limit_choices_to={'archive': False, 'delete_mark': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='res.resource'),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='service',
            field=models.ForeignKey(blank=True, help_text='Linked Service object', limit_choices_to={'archive': False, 'delete_mark': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='equipment.service'),
        ),
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['equipment'], name='qrcode_equipment'),
        ),
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['resource'], name='qrcode_resource'),
        ),
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['service'], name='qrcode_service'),
        ),
    ]
