# Generated by Django 4.2.23 on 2025-10-11 19:04

from django.db import migrations, models, connection
import django.db.models.deletion


def add_qrcode_foreign_keys(apps, schema_editor):
    """
    Add foreign key fields to qr_qrcode table using raw SQL.
    This prevents foreign key constraint errors on production systems.
    """
    with connection.cursor() as cursor:
        # Check if table exists
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.tables 
            WHERE table_schema = DATABASE() 
            AND table_name = 'qr_qrcode'
        """)
        
        table_exists = cursor.fetchone()[0] > 0
        
        if table_exists:
            # Add equipment_id column if it doesn't exist
            cursor.execute("""
                SELECT COUNT(*) 
                FROM information_schema.columns 
                WHERE table_schema = DATABASE() 
                AND table_name = 'qr_qrcode' 
                AND column_name = 'equipment_id'
            """)
            
            if cursor.fetchone()[0] == 0:
                cursor.execute("ALTER TABLE qr_qrcode ADD COLUMN equipment_id char(32) NULL")
                print("Added equipment_id column to qr_qrcode")
            
            # Add resource_id column if it doesn't exist
            cursor.execute("""
                SELECT COUNT(*) 
                FROM information_schema.columns 
                WHERE table_schema = DATABASE() 
                AND table_name = 'qr_qrcode' 
                AND column_name = 'resource_id'
            """)
            
            if cursor.fetchone()[0] == 0:
                cursor.execute("ALTER TABLE qr_qrcode ADD COLUMN resource_id char(32) NULL")
                print("Added resource_id column to qr_qrcode")
            
            # Add service_id column if it doesn't exist
            cursor.execute("""
                SELECT COUNT(*) 
                FROM information_schema.columns 
                WHERE table_schema = DATABASE() 
                AND table_name = 'qr_qrcode' 
                AND column_name = 'service_id'
            """)
            
            if cursor.fetchone()[0] == 0:
                cursor.execute("ALTER TABLE qr_qrcode ADD COLUMN service_id char(32) NULL")
                print("Added service_id column to qr_qrcode")
            
            # Add indexes
            try:
                cursor.execute("CREATE INDEX qrcode_equipment ON qr_qrcode (equipment_id)")
                print("Created qrcode_equipment index")
            except Exception as e:
                print(f"Index qrcode_equipment might already exist: {e}")
            
            try:
                cursor.execute("CREATE INDEX qrcode_resource ON qr_qrcode (resource_id)")
                print("Created qrcode_resource index")
            except Exception as e:
                print(f"Index qrcode_resource might already exist: {e}")
            
            try:
                cursor.execute("CREATE INDEX qrcode_service ON qr_qrcode (service_id)")
                print("Created qrcode_service index")
            except Exception as e:
                print(f"Index qrcode_service might already exist: {e}")
            
            print("Updated qr_qrcode table with foreign key columns")
        else:
            print("qr_qrcode table does not exist, skipping foreign key additions")


def reverse_add_qrcode_foreign_keys(apps, schema_editor):
    """
    Reverse operation - remove foreign key columns
    """
    with connection.cursor() as cursor:
        # Check if table exists
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.tables 
            WHERE table_schema = DATABASE() 
            AND table_name = 'qr_qrcode'
        """)
        
        table_exists = cursor.fetchone()[0] > 0
        
        if table_exists:
            # Drop indexes first
            try:
                cursor.execute("DROP INDEX qrcode_equipment ON qr_qrcode")
            except:
                pass
            
            try:
                cursor.execute("DROP INDEX qrcode_resource ON qr_qrcode")
            except:
                pass
            
            try:
                cursor.execute("DROP INDEX qrcode_service ON qr_qrcode")
            except:
                pass
            
            # Drop columns
            try:
                cursor.execute("ALTER TABLE qr_qrcode DROP COLUMN equipment_id")
            except:
                pass
            
            try:
                cursor.execute("ALTER TABLE qr_qrcode DROP COLUMN resource_id")
            except:
                pass
            
            try:
                cursor.execute("ALTER TABLE qr_qrcode DROP COLUMN service_id")
            except:
                pass
            
            print("Removed foreign key columns from qr_qrcode")


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0038_alter_equipment_delete_mark_and_more'),
        ('res', '0031_alter_resource_delete_mark_and_more'),
        ('qr', '0031_delete_qrservicelink'),
    ]

    operations = [
        migrations.RunPython(
            add_qrcode_foreign_keys,
            reverse_add_qrcode_foreign_keys,
        ),
    ]
