# Generated by Django 5.2.7 on 2025-10-11 20:58

from django.db import migrations, models, connection


def create_qrcode_operations_table(apps, schema_editor):
    """
    Create qr_qrcode_operations many-to-many table using raw SQL.
    This prevents foreign key constraint errors on production systems.
    """
    with connection.cursor() as cursor:
        # Check if table exists
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.tables 
            WHERE table_schema = DATABASE() 
            AND table_name = 'qr_qrcode_operations'
        """)
        
        table_exists = cursor.fetchone()[0] > 0
        
        if not table_exists:
            # Create the many-to-many table
            cursor.execute("""
                CREATE TABLE `qr_qrcode_operations` (
                    `id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY,
                    `qrcode_id` char(32) NOT NULL,
                    `operation_id` char(32) NOT NULL
                )
            """)
            
            # Create indexes
            try:
                cursor.execute("CREATE INDEX `qr_qrcode_operations_qrcode_id` ON `qr_qrcode_operations` (`qrcode_id`)")
                print("Created qrcode_operations_qrcode_id index")
            except Exception as e:
                print(f"Index qrcode_operations_qrcode_id might already exist: {e}")
            
            try:
                cursor.execute("CREATE INDEX `qr_qrcode_operations_operation_id` ON `qr_qrcode_operations` (`operation_id`)")
                print("Created qrcode_operations_operation_id index")
            except Exception as e:
                print(f"Index qrcode_operations_operation_id might already exist: {e}")
            
            # Create unique constraint
            try:
                cursor.execute("ALTER TABLE `qr_qrcode_operations` ADD CONSTRAINT `qr_qrcode_operations_qrcode_id_operation_id` UNIQUE (`qrcode_id`, `operation_id`)")
                print("Created unique constraint for qrcode_operations")
            except Exception as e:
                print(f"Unique constraint might already exist: {e}")
            
            print("Created qr_qrcode_operations table")
        else:
            print("qr_qrcode_operations table already exists, skipping creation")


def reverse_create_qrcode_operations_table(apps, schema_editor):
    """
    Reverse operation - drop the table
    """
    with connection.cursor() as cursor:
        # Check if table exists
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.tables 
            WHERE table_schema = DATABASE() 
            AND table_name = 'qr_qrcode_operations'
        """)
        
        table_exists = cursor.fetchone()[0] > 0
        
        if table_exists:
            cursor.execute("DROP TABLE qr_qrcode_operations")
            print("Dropped qr_qrcode_operations table")


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0032_qrcode_equipment_qrcode_resource_qrcode_service_and_more'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            create_qrcode_operations_table,
            reverse_create_qrcode_operations_table,
        ),
    ]
