# Generated by Django 5.2.7 on 2025-10-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0032_qrcode_equipment_qrcode_resource_qrcode_service_and_more'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='operations',
            field=models.ManyToManyField(blank=True, help_text='Operations associated with this QR code', related_name='qr_codes_operations', to='service.operation', verbose_name='Operations'),
        ),
    ]
