# Generated by Django 5.2.7 on 2025-10-12 19:16

from django.db import migrations, connection


def fix_qrservicelink_table(apps, schema_editor):
    """
    Fix QRServiceLink table issue on production systems.
    If the table exists, drop it to allow proper migration flow.
    """
    with connection.cursor() as cursor:
        # Check if table exists
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.tables 
            WHERE table_schema = DATABASE() 
            AND table_name = 'qr_qrservicelink'
        """)
        
        table_exists = cursor.fetchone()[0] > 0
        
        if table_exists:
            # Drop the table if it exists
            cursor.execute("DROP TABLE IF EXISTS qr_qrservicelink")
            print("Dropped existing qr_qrservicelink table")


def reverse_fix_qrservicelink_table(apps, schema_editor):
    """
    Reverse operation - do nothing as we don't want to recreate the table
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0033_qrcode_operations'),
    ]

    operations = [
        migrations.RunPython(
            fix_qrservicelink_table,
            reverse_fix_qrservicelink_table,
        ),
    ]
