# Generated by Django 5.0.3 on 2025-02-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='is_folder',
            field=models.BooleanField(default=False),
        ),
    ]
