# Generated by Django 5.0.4 on 2025-02-19 06:01

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_equipment_is_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='model',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='type', chained_model_field='equipment_type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipments', to='equipment.equipmentmodel'),
        ),
    ]
