# Generated by Django 5.0.3 on 2025-04-11 06:28

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_equipment_equip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equip_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Equipment code'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='model', chained_model_field='model', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipments', to='equipment.equipmenttype'),
        ),
    ]
