# Generated by Django 5.0.3 on 2025-04-11 07:35

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_alter_equipment_equip_code_alter_equipment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='model',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='type', chained_model_field='type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipments', to='equipment.equipmentmodel'),
        ),
    ]
