# Generated by Django 5.0.4 on 2025-07-07 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0014_alter_equipment_modified_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='modified_time',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='equipmentmodel',
            old_name='modified_time',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='equipmenttype',
            old_name='modified_time',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='interface',
            old_name='modified_time',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='interfacetype',
            old_name='modified_time',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='modified_time',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='software',
            old_name='modified_time',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='softwareversion',
            old_name='modified_time',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='modified_time',
            new_name='modified',
        ),
    ]
