# Generated by Django 5.0.3 on 2025-08-05 11:31

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0031_alter_equipment_created_alter_equipmentmodel_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='software_version',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_model_field='software', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='equipment.softwareversion'),
        ),
    ]
