# Generated by Django 5.0.3 on 2025-07-01 12:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='guid_public_code',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='short_public_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
