# Generated by Django 5.0.4 on 2025-07-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0005_alter_qrcode_modified_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='modified_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='qrtype',
            name='modified_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
