# Generated by Django 5.0.4 on 2025-07-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0006_alter_qrcode_modified_time_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['short_public_code'], name='short_public_code'),
        ),
    ]
