# Generated by Django 5.0.4 on 2025-07-07 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0008_qrcode_operation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qrcode',
            old_name='modified_time',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='qrtype',
            old_name='modified_time',
            new_name='modified',
        ),
    ]
