# Generated by Django 5.0.4 on 2025-07-29 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0010_qrcode_created_qrtype_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 29, 21, 48, 6, 686266), editable=False),
        ),
        migrations.AlterField(
            model_name='qrtype',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 29, 21, 48, 6, 686266), editable=False),
        ),
    ]
