# Generated by Django 4.2.23 on 2025-10-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0025_alter_qrcode_created_alter_qrtype_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='archive',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='qrtype',
            name='archive',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='qrtype',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='qrtype',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='qrtype',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='qrtype',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
    ]
