# Generated by Django 4.2.23 on 2025-10-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0026_alter_qrcode_archive_alter_qrcode_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='delete_mark',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='qrtype',
            name='delete_mark',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
