# Generated by Django 5.2.7 on 2025-10-11 18:24

from django.db import migrations, connection


def alter_qrservicelink_unique_together(apps, schema_editor):
    """
    Remove unique constraints from qr_qrservicelink table if they exist.
    This prevents errors when the table was created with raw SQL.
    """
    with connection.cursor() as cursor:
        # Check if table exists
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.tables 
            WHERE table_schema = DATABASE() 
            AND table_name = 'qr_qrservicelink'
        """)
        
        table_exists = cursor.fetchone()[0] > 0
        
        if table_exists:
            # Check for existing unique constraints and drop them
            cursor.execute("""
                SELECT CONSTRAINT_NAME 
                FROM information_schema.TABLE_CONSTRAINTS 
                WHERE TABLE_SCHEMA = DATABASE() 
                AND TABLE_NAME = 'qr_qrservicelink' 
                AND CONSTRAINT_TYPE = 'UNIQUE'
            """)
            
            constraints = cursor.fetchall()
            for constraint in constraints:
                constraint_name = constraint[0]
                cursor.execute(f"ALTER TABLE qr_qrservicelink DROP INDEX `{constraint_name}`")
                print(f"Dropped unique constraint: {constraint_name}")
            
            print("Updated qr_qrservicelink unique constraints")
        else:
            print("qr_qrservicelink table does not exist, skipping unique constraint changes")


def reverse_alter_qrservicelink_unique_together(apps, schema_editor):
    """
    Reverse operation - recreate unique constraints
    """
    with connection.cursor() as cursor:
        # Check if table exists
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.tables 
            WHERE table_schema = DATABASE() 
            AND table_name = 'qr_qrservicelink'
        """)
        
        table_exists = cursor.fetchone()[0] > 0
        
        if table_exists:
            # Recreate unique constraints
            cursor.execute("ALTER TABLE qr_qrservicelink ADD UNIQUE KEY `qr_qrservicelink_qr_code_id_equipment_id` (`qr_code_id`, `equipment_id`)")
            cursor.execute("ALTER TABLE qr_qrservicelink ADD UNIQUE KEY `qr_qrservicelink_qr_code_id_service_id` (`qr_code_id`, `service_id`)")
            print("Recreated unique constraints for qr_qrservicelink")


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0029_qrservicelink'),
    ]

    operations = [
        migrations.RunPython(
            alter_qrservicelink_unique_together,
            reverse_alter_qrservicelink_unique_together,
        ),
    ]
