# Generated by Django 4.2.23 on 2025-10-11 18:58

from django.db import migrations, connection


def delete_qrservicelink_table(apps, schema_editor):
    """
    Delete QRServiceLink table if it exists.
    This prevents errors when Django doesn't recognize the model.
    """
    with connection.cursor() as cursor:
        # Check if table exists
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.tables 
            WHERE table_schema = DATABASE() 
            AND table_name = 'qr_qrservicelink'
        """)
        
        table_exists = cursor.fetchone()[0] > 0
        
        if table_exists:
            # Drop the table
            cursor.execute("DROP TABLE qr_qrservicelink")
            print("Dropped qr_qrservicelink table")
        else:
            print("qr_qrservicelink table does not exist, skipping deletion")


def reverse_delete_qrservicelink_table(apps, schema_editor):
    """
    Reverse operation - recreate the table
    """
    with connection.cursor() as cursor:
        # Check if table exists
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.tables 
            WHERE table_schema = DATABASE() 
            AND table_name = 'qr_qrservicelink'
        """)
        
        table_exists = cursor.fetchone()[0] > 0
        
        if not table_exists:
            # Recreate the table
            cursor.execute("""
                CREATE TABLE `qr_qrservicelink` (
                    `guid` char(32) NOT NULL PRIMARY KEY,
                    `modified` datetime(6) NOT NULL,
                    `created` datetime(6) NOT NULL,
                    `code` varchar(9) NOT NULL,
                    `name` varchar(32) NOT NULL,
                    `delete_mark` bool NOT NULL,
                    `link_type` varchar(20) NOT NULL,
                    `description` longtext NOT NULL,
                    `is_primary` bool NOT NULL,
                    `archive` bool NOT NULL,
                    `equipment_id` char(32) NULL,
                    `qr_code_id` char(32) NOT NULL,
                    `service_id` char(32) NULL
                )
            """)
            print("Recreated qr_qrservicelink table")


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0030_alter_qrservicelink_unique_together'),
    ]

    operations = [
        migrations.RunPython(
            delete_qrservicelink_table,
            reverse_delete_qrservicelink_table,
        ),
    ]
