# Generated by Django 5.2.7 on 2025-10-14 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram", "0002_telegramuser_employee_telegramuser_phone_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramSubscriptionCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Category Code"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Category Name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "is_public",
                    models.BooleanField(
                        default=True, verbose_name="Public Subscription"
                    ),
                ),
                (
                    "requires_approval",
                    models.BooleanField(
                        default=False, verbose_name="Requires Approval"
                    ),
                ),
                (
                    "icon",
                    models.CharField(default="📢", max_length=10, verbose_name="Icon"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Telegram Subscription Category",
                "verbose_name_plural": "Telegram Subscription Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TelegramBroadcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Broadcast Title"),
                ),
                ("message", models.TextField(verbose_name="Message Content")),
                (
                    "broadcast_type",
                    models.CharField(
                        choices=[
                            ("category", "Category Broadcast"),
                            ("individual", "Individual Message"),
                            ("bulk", "Bulk Message"),
                            ("scheduled", "Scheduled Message"),
                        ],
                        default="category",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Scheduled Time"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Sent Time"
                    ),
                ),
                ("total_recipients", models.IntegerField(default=0)),
                ("delivered_count", models.IntegerField(default=0)),
                ("failed_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_broadcasts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="targeted_broadcasts",
                        to="telegram.telegramuser",
                    ),
                ),
                (
                    "target_categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="broadcasts",
                        to="telegram.telegramsubscriptioncategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Telegram Broadcast",
                "verbose_name_plural": "Telegram Broadcasts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TelegramMessageTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Template Name"),
                ),
                (
                    "subject_template",
                    models.CharField(max_length=200, verbose_name="Subject Template"),
                ),
                ("message_template", models.TextField(verbose_name="Message Template")),
                (
                    "variables",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Available Variables"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates",
                        to="telegram.telegramsubscriptioncategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Telegram Message Template",
                "verbose_name_plural": "Telegram Message Templates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TelegramBroadcastDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("blocked", "Blocked"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("telegram_message_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "broadcast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="telegram.telegrambroadcast",
                    ),
                ),
                (
                    "telegram_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="broadcast_deliveries",
                        to="telegram.telegramuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Telegram Broadcast Delivery",
                "verbose_name_plural": "Telegram Broadcast Deliveries",
                "ordering": ["-sent_at"],
                "unique_together": {("broadcast", "telegram_user")},
            },
        ),
        migrations.CreateModel(
            name="TelegramUserSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("unsubscribed", "Unsubscribed"),
                            ("pending", "Pending Approval"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("subscribed_at", models.DateTimeField(auto_now_add=True)),
                ("unsubscribed_at", models.DateTimeField(blank=True, null=True)),
                ("last_notification_at", models.DateTimeField(blank=True, null=True)),
                ("notification_count", models.IntegerField(default=0)),
                ("preferences", models.JSONField(blank=True, default=dict)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscribers",
                        to="telegram.telegramsubscriptioncategory",
                    ),
                ),
                (
                    "telegram_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="telegram.telegramuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Telegram User Subscription",
                "verbose_name_plural": "Telegram User Subscriptions",
                "ordering": ["-subscribed_at"],
                "unique_together": {("telegram_user", "category")},
            },
        ),
    ]
