# Generated by Django 5.2.7 on 2025-10-14 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram", "0003_telegramsubscriptioncategory_telegrambroadcast_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Permission Name"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Permission Code"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "permission_type",
                    models.CharField(
                        choices=[
                            ("command", "Command"),
                            ("feature", "Feature"),
                            ("data_access", "Data Access"),
                            ("admin", "Administrative"),
                        ],
                        default="command",
                        max_length=20,
                    ),
                ),
                (
                    "required_roles",
                    models.JSONField(default=list, verbose_name="Required Roles"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
            ],
            options={
                "verbose_name": "Telegram Permission",
                "verbose_name_plural": "Telegram Permissions",
                "ordering": ["permission_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="TelegramUserGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Group Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("roles", models.JSONField(default=list, verbose_name="Allowed Roles")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Telegram User Group",
                "verbose_name_plural": "Telegram User Groups",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TelegramAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("command", "Command Execution"),
                            ("permission_check", "Permission Check"),
                            ("role_assignment", "Role Assignment"),
                            ("group_membership", "Group Membership Change"),
                            ("data_access", "Data Access"),
                        ],
                        max_length=20,
                        verbose_name="Action Type",
                    ),
                ),
                ("action", models.CharField(max_length=100, verbose_name="Action")),
                (
                    "details",
                    models.JSONField(blank=True, default=dict, verbose_name="Details"),
                ),
                ("success", models.BooleanField(default=True, verbose_name="Success")),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Error Message"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Address"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "telegram_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="telegram.telegramuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Telegram Audit Log",
                "verbose_name_plural": "Telegram Audit Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TelegramUserGroupMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assigned_roles",
                    models.JSONField(default=list, verbose_name="Assigned Roles"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "assigned_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Assigned At"),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_telegram_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assigned By",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="telegram.telegramusergroup",
                    ),
                ),
                (
                    "telegram_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_memberships",
                        to="telegram.telegramuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Telegram User Group Membership",
                "verbose_name_plural": "Telegram User Group Memberships",
                "ordering": ["-assigned_at"],
                "unique_together": {("telegram_user", "group")},
            },
        ),
    ]
