# Generated by Django 4.2.23 on 2025-10-14 08:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


def populate_guid_and_code(apps, schema_editor):
    """Populate guid and code fields for existing records"""
    TelegramMessage = apps.get_model('telegram', 'TelegramMessage')
    for message in TelegramMessage.objects.all():
        if not message.guid:
            message.guid = uuid.uuid4()
        if not message.code:
            # Generate a simple code based on message_id
            message.code = f"TG{message.message_id:06d}"
        if not message.name:
            message.name = f"Message {message.message_id}"
        message.save()


def reverse_populate_guid_and_code(apps, schema_editor):
    """Reverse operation - no need to do anything"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0004_telegrampermission_telegramusergroup_and_more'),
    ]

    operations = [
        # First, add new fields as nullable
        migrations.AddField(
            model_name='telegrammessage',
            name='guid',
            field=models.UUIDField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='code',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='delete_mark',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        
        # Populate the new fields
        migrations.RunPython(populate_guid_and_code, reverse_populate_guid_and_code),
        
        # Remove the old id field first (since we now have guid as primary key)
        migrations.RemoveField(
            model_name='telegrammessage',
            name='id',
        ),
        
        # Make guid non-nullable and primary key
        migrations.AlterField(
            model_name='telegrammessage',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        
        # Make code non-nullable and add index
        migrations.AlterField(
            model_name='telegrammessage',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=9),
        ),
        
        # Make name non-nullable and add index
        migrations.AlterField(
            model_name='telegrammessage',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        
        # Add index to delete_mark
        migrations.AlterField(
            model_name='telegrammessage',
            name='delete_mark',
            field=models.BooleanField(db_index=True, default=False),
        ),
        
        # Remove the old created_at field
        migrations.RemoveField(
            model_name='telegrammessage',
            name='created_at',
        ),
    ]
