# Generated by Django 4.2.23 on 2025-01-14 09:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


def populate_guid_and_code(apps, schema_editor):
    """Populate guid and code fields for existing records"""
    TelegramMessageTemplate = apps.get_model('telegram', 'TelegramMessageTemplate')
    for template in TelegramMessageTemplate.objects.all():
        if not template.guid:
            template.guid = uuid.uuid4()
        if not template.code:
            # Generate a simple code based on name
            template.code = f"TMP{template.name[:6].upper().replace(' ', '')}"
        template.save()


def reverse_populate_guid_and_code(apps, schema_editor):
    """Reverse operation - no need to do anything"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0005_change_telegrammessage_inheritance'),
    ]

    operations = [
        # First, add new fields as nullable
        migrations.AddField(
            model_name='telegrammessagetemplate',
            name='guid',
            field=models.UUIDField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='telegrammessagetemplate',
            name='code',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='telegrammessagetemplate',
            name='delete_mark',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telegrammessagetemplate',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='telegrammessagetemplate',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        
        # Populate the new fields
        migrations.RunPython(populate_guid_and_code, reverse_populate_guid_and_code),
        
        # Remove the old id field first (since we now have guid as primary key)
        migrations.RemoveField(
            model_name='telegrammessagetemplate',
            name='id',
        ),
        
        # Make guid non-nullable and primary key
        migrations.AlterField(
            model_name='telegrammessagetemplate',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        
        # Make code non-nullable and add index
        migrations.AlterField(
            model_name='telegrammessagetemplate',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=9),
        ),
        
        # Make existing name field have index
        migrations.AlterField(
            model_name='telegrammessagetemplate',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        
        # Add index to delete_mark
        migrations.AlterField(
            model_name='telegrammessagetemplate',
            name='delete_mark',
            field=models.BooleanField(db_index=True, default=False),
        ),
        
        # Remove the old created_at and updated_at fields
        migrations.RemoveField(
            model_name='telegrammessagetemplate',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='telegrammessagetemplate',
            name='updated_at',
        ),
    ]
