# Generated by Django 4.2.23 on 2025-01-14 15:30

from django.db import migrations, models


def populate_created_field(apps, schema_editor):
    """Populate created field with values from created_at"""
    TelegramBroadcast = apps.get_model('telegram', 'TelegramBroadcast')
    
    for broadcast in TelegramBroadcast.objects.all():
        if not broadcast.created:
            broadcast.created = broadcast.created_at
            broadcast.save()


def reverse_populate_created_field(apps, schema_editor):
    """Reverse operation - not needed for this migration"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0006_change_telegrammessagetemplate_inheritance'),
    ]

    operations = [
        # Add created field as nullable first
        migrations.AddField(
            model_name='telegrambroadcast',
            name='created',
            field=models.DateTimeField(null=True, blank=True, auto_now_add=True),
        ),
        
        # Populate the new field
        migrations.RunPython(populate_created_field, reverse_populate_created_field),
        
        # Make field non-nullable
        migrations.AlterField(
            model_name='telegrambroadcast',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
