# Generated by Django 4.2.23 on 2025-01-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0007_add_created_field_to_broadcast'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambroadcast',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=32, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='telegrambroadcast',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=9, verbose_name='Code'),
        ),
    ]
