# Generated by Django 4.2.23 on 2025-01-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0008_add_name_and_code_to_broadcast'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambroadcast',
            name='delete_mark',
            field=models.BooleanField(default=False, db_index=True, verbose_name='Delete Mark'),
        ),
        migrations.AddField(
            model_name='telegrambroadcast',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified'),
        ),
    ]
