# Generated by Django 4.2.23 on 2025-01-14 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0010_add_guid_to_broadcast'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegrambroadcast',
            name='guid',
        ),
    ]
