# Generated by Django 5.2.7 on 2025-10-15 06:13

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtSystem',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('enabled', models.BooleanField(default=True)),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_ping_datetime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'External System',
            },
        ),
    ]
