# Generated by Django 5.0.4 on 2024-05-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extsystem',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
