# Generated by Django 5.0.4 on 2024-06-05 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extsystem',
            name='token',
        ),
        migrations.AddField(
            model_name='extsystem',
            name='created_datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='extsystem',
            name='last_ping_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
