# Generated by Django 5.0.4 on 2024-05-01 13:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_extsystem_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extsystem',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='extsystem',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
