# Generated by Django 5.0.3 on 2024-05-21 10:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_alter_extsystem_guid_alter_extsystem_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extsystem',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
