# Generated by Django 5.0.4 on 2025-08-22 03:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_alter_extsystem_last_ping_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extsystem',
            name='created_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 22, 3, 5, 25, 263156, tzinfo=datetime.timezone.utc)),
        ),
    ]
