# Generated by Django 5.2.7 on 2025-10-15 06:13

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessProfile',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('code', models.CharField(blank=True, db_index=True, max_length=9)),
                ('delete_mark', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(blank=True, db_index=True, max_length=150)),
                ('create_date', models.DateField(default=datetime.date.today, help_text='Create date', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Expiry date', null=True)),
                ('archive', models.BooleanField(db_index=True, default=False)),
                ('comment', models.TextField(blank=True)),
                ('help_text', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Access Profile',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('code', models.CharField(blank=True, db_index=True, max_length=9)),
                ('delete_mark', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(blank=True, db_index=True, max_length=50)),
                ('technical', models.BooleanField(default=False, help_text='Technical account')),
                ('create_date', models.DateField(default=datetime.date.today, help_text='Create date', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Expiry date', null=True)),
                ('disabled', models.BooleanField(default=False)),
                ('archive', models.BooleanField(db_index=True, default=False)),
                ('comment', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Account',
            },
        ),
    ]
