# Generated by Django 5.2.7 on 2025-10-12 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acc', '0001_initial'),
        ('org', '0001_initial'),
        ('res', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessprofile',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Profile groups', related_name='profiles', to='res.resourcegroup'),
        ),
        migrations.AddField(
            model_name='accessprofile',
            name='resource',
            field=models.ForeignKey(help_text='Resource', on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='res.resource'),
        ),
        migrations.AddField(
            model_name='account',
            name='employee',
            field=models.ForeignKey(help_text='Employee', on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='org.employee'),
        ),
        migrations.AddField(
            model_name='account',
            name='profiles',
            field=models.ManyToManyField(blank=True, related_name='accounts', to='acc.accessprofile'),
        ),
        migrations.AddField(
            model_name='account',
            name='resource',
            field=models.ForeignKey(help_text='Resource', limit_choices_to={'accounts_provider': True}, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='res.resource'),
        ),
    ]
