# Generated by Django 5.0.4 on 2024-09-11 16:51

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0003_alter_account_profiles'),
        ('res', '0005_resource_accounts_provider_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceGroup',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=9)),
                ('delete_mark', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=150)),
                ('create_date', models.DateField(default=datetime.date.today, help_text='Create date', null=True)),
                ('technical', models.BooleanField(default=False, help_text='Technical group')),
                ('archive', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('resource', models.ForeignKey(help_text='Resource', on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='res.resource')),
            ],
            options={
                'verbose_name': 'Resource Group',
            },
        ),
        migrations.AddField(
            model_name='accessprofile',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Profile groups', limit_choices_to={'resource': models.ForeignKey(help_text='Resource', on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='res.resource')}, related_name='profiles', to='acc.resourcegroup'),
        ),
    ]
