# Generated by Django 5.0.4 on 2024-09-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0005_alter_resourcegroup_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessprofile',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Profile groups', related_name='profiles', to='acc.resourcegroup'),
        ),
    ]
