# Generated by Django 5.0.4 on 2025-07-03 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0007_alter_accessprofile_groups_delete_resourcegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessprofile',
            name='modified_time',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AddField(
            model_name='account',
            name='modified_time',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
