# Generated by Django 5.0.4 on 2025-07-07 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0010_alter_accessprofile_modified_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessprofile',
            old_name='modified_time',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='modified_time',
            new_name='modified',
        ),
    ]
