# Generated by Django 5.0.3 on 2025-07-31 05:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0024_alter_accessprofile_created_alter_account_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessprofile',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 31, 5, 47, 14, 489809, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 31, 5, 47, 14, 489809, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
