# Generated by Django 5.0.3 on 2025-08-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0026_alter_accessprofile_created_alter_account_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessprofile',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
