# Generated by Django 4.2.23 on 2025-10-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0028_alter_accessprofile_archive_alter_accessprofile_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessprofile',
            name='delete_mark',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='delete_mark',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
