# Generated by Django 5.2.7 on 2025-10-12 19:33

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('code', models.CharField(blank=True, db_index=True, max_length=9)),
                ('delete_mark', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(blank=True, db_index=True, max_length=150)),
                ('archive', models.BooleanField(db_index=True, default=False, help_text='Is archived')),
            ],
            options={
                'verbose_name': 'Organization',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('code', models.CharField(blank=True, db_index=True, max_length=9)),
                ('delete_mark', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=150)),
                ('archive', models.BooleanField(default=False, help_text='Is archived')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='org.department')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='org.organization')),
            ],
            options={
                'verbose_name': 'Department',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('code', models.CharField(blank=True, db_index=True, max_length=9)),
                ('delete_mark', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(db_index=True, help_text='Full name', max_length=150)),
                ('archive', models.BooleanField(db_index=True, default=False, help_text='Is archived')),
                ('start_date', models.DateField(default=datetime.date.today, help_text='Work till', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Fired date', null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='org.department')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='org.organization')),
            ],
            options={
                'verbose_name': 'Employee',
                'ordering': ['name'],
            },
        ),
    ]
