# Generated by Django 4.2.23 on 2025-10-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, db_index=True, help_text='Phone number for Telegram', max_length=20),
        ),
    ]
