# Generated by Django 4.2.23 on 2025-10-13 13:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0002_employee_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, db_index=True, help_text='Phone number for Telegram (format: 79161234567 or +79161234567)', max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (e.g., 79161234567 or +79161234567)', regex='^(\\+?7|8)?[0-9]{10}$')]),
        ),
    ]
