# Generated by Django 4.2.23 on 2025-01-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0003_alter_employee_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, db_index=True, help_text='Email address', max_length=254, verbose_name='Email'),
        ),
    ]
