# Generated by Django 5.0.4 on 2024-05-13 16:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0004_remove_department_is_group_alter_department_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=9)),
                ('delete_mark', models.BooleanField(default=False)),
                ('is_group', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=150)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='org.department')),
                ('parent', models.ForeignKey(blank=True, limit_choices_to={'is_group': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='org.employee')),
            ],
            options={
                'verbose_name': 'Employee',
            },
        ),
    ]
