# Generated by Django 5.0.4 on 2025-07-03 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0005_alter_employee_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='modified_time',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='modified_time',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='modified_time',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
