# Generated by Django 5.0.4 on 2025-07-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0006_department_modified_time_employee_modified_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='modified_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='modified_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='modified_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
