# Generated by Django 5.0.4 on 2025-07-07 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0008_alter_department_modified_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='modified_time',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='modified_time',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='modified_time',
            new_name='modified',
        ),
    ]
