# Generated by Django 5.0.3 on 2025-07-31 05:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0022_alter_department_created_alter_employee_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 31, 5, 47, 14, 489809, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 31, 5, 47, 14, 489809, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 31, 5, 47, 14, 489809, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
