# Generated by Django 5.0.4 on 2025-08-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0026_alter_employee_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='archive',
            field=models.BooleanField(default=False, help_text='Is archived'),
        ),
        migrations.AddField(
            model_name='organization',
            name='archive',
            field=models.BooleanField(default=False, help_text='Is archived'),
        ),
    ]
