# Generated by Django 5.0.4 on 2025-08-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0027_department_archive_organization_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(db_index=True, help_text='Full name', max_length=150),
        ),
    ]
