# Generated by Django 5.0.4 on 2025-08-28 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0028_alter_employee_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['name'], 'verbose_name': 'Employee'},
        ),
    ]
