# Generated by Django 4.2.23 on 2025-10-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0030_alter_department_code_alter_department_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='delete_mark',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='delete_mark',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='delete_mark',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
