# Generated by Django 5.2.7 on 2025-10-15 10:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Permission Name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Permission Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('permission_type', models.CharField(choices=[('command', 'Command'), ('feature', 'Feature'), ('data_access', 'Data Access'), ('admin', 'Administrative')], default='command', max_length=20, verbose_name='Permission Type')),
                ('required_roles', models.JSONField(default=list, verbose_name='Required Roles')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Telegram Permission',
                'verbose_name_plural': 'Telegram Permissions',
                'ordering': ['permission_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TelegramSubscriptionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Category Code')),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_public', models.BooleanField(default=True, verbose_name='Public Subscription')),
                ('requires_approval', models.BooleanField(default=False, verbose_name='Requires Approval')),
                ('icon', models.CharField(default='📢', max_length=10, verbose_name='Icon')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Telegram Subscription Category',
                'verbose_name_plural': 'Telegram Subscription Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TelegramUserGroup',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('code', models.CharField(blank=True, db_index=True, max_length=9)),
                ('name', models.CharField(blank=True, db_index=True, max_length=32)),
                ('delete_mark', models.BooleanField(db_index=True, default=False)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Telegram User Group',
                'verbose_name_plural': 'Telegram User Groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TelegramMessageTemplate',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('code', models.CharField(blank=True, db_index=True, max_length=9)),
                ('name', models.CharField(blank=True, db_index=True, max_length=32)),
                ('delete_mark', models.BooleanField(db_index=True, default=False)),
                ('subject_template', models.CharField(max_length=200, verbose_name='Subject Template')),
                ('message_template', models.TextField(verbose_name='Message Template')),
                ('variables', models.JSONField(blank=True, default=list, verbose_name='Available Variables')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='telegram.telegramsubscriptioncategory')),
            ],
            options={
                'verbose_name': 'Telegram Message Template',
                'verbose_name_plural': 'Telegram Message Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('code', models.CharField(blank=True, db_index=True, max_length=9)),
                ('name', models.CharField(blank=True, db_index=True, max_length=32)),
                ('delete_mark', models.BooleanField(db_index=True, default=False)),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=255, verbose_name='Telegram Username')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='Last Name')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_users', to='org.employee', verbose_name='Employee')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telegram User',
                'verbose_name_plural': 'Telegram Users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramMessage',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('code', models.CharField(blank=True, db_index=True, max_length=9)),
                ('name', models.CharField(blank=True, db_index=True, max_length=32)),
                ('delete_mark', models.BooleanField(db_index=True, default=False)),
                ('message_id', models.BigIntegerField(verbose_name='Message ID')),
                ('message_type', models.CharField(choices=[('text', 'Text Message'), ('command', 'Command'), ('callback', 'Callback Query'), ('error', 'Error')], max_length=20, verbose_name='Message Type')),
                ('content', models.TextField(verbose_name='Content')),
                ('response', models.TextField(blank=True, verbose_name='Bot Response')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Processed')),
                ('telegram_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='telegram.telegramuser', verbose_name='Telegram User')),
            ],
            options={
                'verbose_name': 'Telegram Message',
                'verbose_name_plural': 'Telegram Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramBroadcast',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, db_index=True, max_length=9)),
                ('name', models.CharField(blank=True, db_index=True, max_length=32)),
                ('delete_mark', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=200, verbose_name='Broadcast Title')),
                ('message', models.TextField(verbose_name='Message Content')),
                ('broadcast_type', models.CharField(choices=[('category', 'Category Broadcast'), ('individual', 'Individual Message'), ('bulk', 'Bulk Message'), ('scheduled', 'Scheduled Message')], default='category', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Scheduled Time')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent Time')),
                ('total_recipients', models.IntegerField(default=0, verbose_name='Total Recipients')),
                ('delivered_count', models.IntegerField(default=0, verbose_name='Delivered Count')),
                ('failed_count', models.IntegerField(default=0, verbose_name='Failed Count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_broadcasts', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('target_categories', models.ManyToManyField(blank=True, related_name='broadcasts', to='telegram.telegramsubscriptioncategory')),
                ('target_users', models.ManyToManyField(blank=True, related_name='targeted_broadcasts', to='telegram.telegramuser')),
            ],
            options={
                'verbose_name': 'Telegram Broadcast',
                'verbose_name_plural': 'Telegram Broadcasts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('command', 'Command Execution'), ('permission_check', 'Permission Check'), ('role_assignment', 'Role Assignment'), ('group_membership', 'Group Membership Change'), ('data_access', 'Data Access')], max_length=20, verbose_name='Action Type')),
                ('action', models.CharField(max_length=100, verbose_name='Action')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Details')),
                ('success', models.BooleanField(default=True, verbose_name='Success')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('telegram_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='telegram.telegramuser', verbose_name='Telegram User')),
            ],
            options={
                'verbose_name': 'Telegram Audit Log',
                'verbose_name_plural': 'Telegram Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramBroadcastDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('blocked', 'Blocked')], default='pending', max_length=20, verbose_name='Status')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent At')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Delivered At')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('telegram_message_id', models.BigIntegerField(blank=True, null=True, verbose_name='Telegram Message ID')),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='telegram.telegrambroadcast', verbose_name='Broadcast')),
                ('telegram_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_deliveries', to='telegram.telegramuser', verbose_name='Telegram User')),
            ],
            options={
                'verbose_name': 'Telegram Broadcast Delivery',
                'verbose_name_plural': 'Telegram Broadcast Deliveries',
                'ordering': ['-sent_at'],
                'unique_together': {('broadcast', 'telegram_user')},
            },
        ),
        migrations.CreateModel(
            name='TelegramUserGroupMembership',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('code', models.CharField(blank=True, db_index=True, max_length=9)),
                ('name', models.CharField(blank=True, db_index=True, max_length=32)),
                ('delete_mark', models.BooleanField(db_index=True, default=False)),
                ('assigned_roles', models.JSONField(default=list, verbose_name='Assigned Roles')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Assigned At')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_telegram_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='telegram.telegramusergroup', verbose_name='Group')),
                ('telegram_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='telegram.telegramuser', verbose_name='Telegram User')),
            ],
            options={
                'verbose_name': 'Telegram User Group Membership',
                'verbose_name_plural': 'Telegram User Group Memberships',
                'ordering': ['-assigned_at'],
                'unique_together': {('telegram_user', 'group')},
            },
        ),
        migrations.CreateModel(
            name='TelegramUserGroupRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('viewer', 'Viewer'), ('user', 'User'), ('operator', 'Operator'), ('admin', 'Admin'), ('super_admin', 'Super Admin')], max_length=20, verbose_name='Role')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_roles', to='telegram.telegramusergroup', verbose_name='Group')),
            ],
            options={
                'verbose_name': 'Telegram User Group Role',
                'verbose_name_plural': 'Telegram User Group Roles',
                'ordering': ['group__name', 'role'],
                'unique_together': {('group', 'role')},
            },
        ),
        migrations.CreateModel(
            name='TelegramUserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('unsubscribed', 'Unsubscribed'), ('pending', 'Pending Approval')], default='active', max_length=20)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('last_notification_at', models.DateTimeField(blank=True, null=True)),
                ('notification_count', models.IntegerField(default=0)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='telegram.telegramsubscriptioncategory')),
                ('telegram_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='telegram.telegramuser')),
            ],
            options={
                'verbose_name': 'Telegram User Subscription',
                'verbose_name_plural': 'Telegram User Subscriptions',
                'ordering': ['-subscribed_at'],
                'unique_together': {('telegram_user', 'category')},
            },
        ),
    ]
