# Generated by Django 5.2.7 on 2025-10-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramusergroup',
            name='is_default_for_new_users',
            field=models.BooleanField(default=False, verbose_name='Default for New Users'),
        ),
    ]
