# Generated by Django 5.2.7 on 2025-10-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_telegramusergroup_is_default_for_new_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramsubscriptioncategory',
            name='is_auto_subscribe',
            field=models.BooleanField(default=False, verbose_name='Auto Subscribe for New Users'),
        ),
    ]
