# Generated by Django 5.2.7 on 2025-10-16 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0003_telegramsubscriptioncategory_is_auto_subscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUserRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('viewer', 'Viewer'), ('user', 'User'), ('operator', 'Operator'), ('admin', 'Admin'), ('super_admin', 'Super Admin')], max_length=20, verbose_name='Role')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('telegram_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='telegram.telegramuser', verbose_name='Telegram User')),
            ],
            options={
                'verbose_name': 'Telegram User Role Assignment',
                'verbose_name_plural': 'Telegram User Role Assignments',
                'ordering': ['telegram_user__user__username', 'role'],
                'unique_together': {('telegram_user', 'role')},
            },
        ),
    ]
