# Generated by Django 5.2.7 on 2025-10-16 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0004_telegramuserroleassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramusergroupmembership',
            name='assigned_roles',
        ),
    ]
