# Generated by Django 5.2.7 on 2025-10-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0005_remove_telegramusergroupmembership_assigned_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramusergrouprole',
            name='is_exclusion',
            field=models.BooleanField(default=False, help_text='If True, this role will be excluded from users in this group. Exclusion has higher priority than inclusion.', verbose_name='Role Exclusion'),
        ),
        migrations.AlterField(
            model_name='telegramusergrouprole',
            name='role',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('user', 'User'), ('operator', 'Operator'), ('admin', 'Admin'), ('super_admin', 'Super Admin'), ('new_user', 'New User'), ('invited_user', 'Invited User'), ('external_user', 'External User')], max_length=20, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='telegramuserroleassignment',
            name='role',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('user', 'User'), ('operator', 'Operator'), ('admin', 'Admin'), ('super_admin', 'Super Admin'), ('new_user', 'New User'), ('invited_user', 'Invited User'), ('external_user', 'External User')], max_length=20, verbose_name='Role'),
        ),
    ]
