# Generated by Django 5.2.7 on 2025-10-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0006_telegramusergrouprole_is_exclusion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='language',
            field=models.CharField(choices=[('ru', 'Russian'), ('en', 'English')], default='ru', help_text='User preferred language for Telegram bot', max_length=2, verbose_name='Language'),
        ),
    ]
