# Generated by Django 4.2.23 on 2025-01-14 16:30

from django.db import migrations, models
import uuid


def populate_guid_field(apps, schema_editor):
    """Populate guid field for existing TelegramBroadcast records"""
    TelegramBroadcast = apps.get_model('telegram', 'TelegramBroadcast')
    
    for broadcast in TelegramBroadcast.objects.all():
        if not broadcast.guid:
            broadcast.guid = str(uuid.uuid4()).replace('-', '')
            broadcast.save()


def reverse_populate_guid_field(apps, schema_editor):
    """Reverse operation - not needed for this migration"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0009_add_delete_mark_and_modified_to_broadcast'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambroadcast',
            name='guid',
            field=models.CharField(blank=True, db_index=True, max_length=32, verbose_name='GUID'),
        ),
        
        # Populate the guid field
        migrations.RunPython(populate_guid_field, reverse_populate_guid_field),
    ]
