# Generated by Django 5.2.7 on 2025-10-12 19:33

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('code', models.CharField(blank=True, db_index=True, max_length=9)),
                ('name', models.CharField(blank=True, db_index=True, max_length=32)),
                ('delete_mark', models.BooleanField(db_index=True, default=False)),
                ('category', models.CharField(choices=[('accounts', 'Accounts'), ('remote', 'Remote resource'), ('local', 'Local'), ('technical', 'Technical'), ('network', 'Sub network'), ('system', 'Information system'), ('routing', 'Routing'), ('management', 'Management and monitoring')], max_length=20)),
            ],
            options={
                'verbose_name': 'Resource Type',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('code', models.CharField(blank=True, db_index=True, max_length=9)),
                ('delete_mark', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(blank=True, db_index=True, max_length=150)),
                ('start_date', models.DateField(default=datetime.date.today, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('accounts_provider', models.BooleanField(default=False)),
                ('resource_category', models.CharField(blank=True, choices=[('accounts', 'Accounts'), ('remote', 'Remote resource'), ('local', 'Local'), ('technical', 'Technical'), ('network', 'Sub network'), ('system', 'Information system'), ('routing', 'Routing'), ('management', 'Management and monitoring')], max_length=20)),
                ('ipv4_address', models.GenericIPAddressField(blank=True, null=True)),
                ('ipv4_gateway', models.GenericIPAddressField(blank=True, null=True)),
                ('ipv4_network_mask', models.IntegerField(default=0)),
                ('dns', models.TextField(blank=True)),
                ('archive', models.BooleanField(db_index=True, default=False)),
                ('comment', models.TextField(blank=True)),
                ('admin_page_url', models.URLField(blank=True)),
                ('cached_full_path_name', models.CharField(blank=True, default='', max_length=150)),
                ('accounts_from', models.ForeignKey(blank=True, limit_choices_to={'accounts_provider': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='res.resource')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='org.employee')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='org.organization')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='equipment.service')),
                ('resource_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='res.resourcetype')),
            ],
            options={
                'verbose_name': 'Resource',
            },
        ),
        migrations.CreateModel(
            name='ResourceGroup',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('code', models.CharField(blank=True, db_index=True, max_length=9)),
                ('delete_mark', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(db_index=True, help_text='Name', max_length=150)),
                ('archive', models.BooleanField(db_index=True, default=False, help_text='Is archived')),
                ('comment', models.TextField(blank=True, help_text='Comment')),
                ('create_date', models.DateField(default=datetime.date.today, help_text='Create date', null=True)),
                ('technical', models.BooleanField(default=False, help_text='Technical group')),
                ('title', models.CharField(blank=True, help_text='Full title', max_length=150)),
                ('resource', models.ForeignKey(help_text='Resource', limit_choices_to={'accounts_provider': True}, on_delete=django.db.models.deletion.CASCADE, to='res.resource')),
            ],
            options={
                'verbose_name': 'Resource Group',
            },
        ),
    ]
