# Generated by Django 5.0.3 on 2024-05-15 08:13

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0017_alter_service_software'),
        ('org', '0007_employee_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=9)),
                ('delete_mark', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=150)),
                ('start_date', models.DateField(default=datetime.date.today, null=True)),
                ('end_date', models.DateField(default=datetime.date.today, null=True)),
                ('ipv4_address', models.GenericIPAddressField(blank=True, null=True)),
                ('ipv4_gateway', models.GenericIPAddressField(blank=True, null=True)),
                ('ipv4_network_mask', models.IntegerField(default=0)),
                ('dns', models.TextField(blank=True)),
                ('archive', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True)),
                ('accounts_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='res.resource')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='org.employee')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='org.organization')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='equipment.service')),
            ],
            options={
                'verbose_name': 'Abstract Catalog model',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
