# Generated by Django 5.0.4 on 2024-06-05 19:53

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=9)),
                ('name', models.CharField(blank=True, max_length=32)),
                ('delete_mark', models.BooleanField(default=False)),
                ('category', models.CharField(blank=True, choices=[('accounts', 'Accounts'), ('remote', 'Remote resource'), ('local', 'Local'), ('technical', 'Technical'), ('network', 'Sub network'), ('system', 'Information system'), ('routing', 'Routing'), ('management', 'Management and monitoring')], max_length=20)),
            ],
            options={
                'verbose_name': 'Resource Type',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=9)),
                ('delete_mark', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('start_date', models.DateField(default=datetime.date.today, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('resource_category', models.CharField(blank=True, choices=[('accounts', 'Accounts'), ('remote', 'Remote resource'), ('local', 'Local'), ('technical', 'Technical'), ('network', 'Sub network'), ('system', 'Information system'), ('routing', 'Routing'), ('management', 'Management and monitoring')], max_length=20)),
                ('ipv4_address', models.GenericIPAddressField(blank=True, null=True)),
                ('ipv4_gateway', models.GenericIPAddressField(blank=True, null=True)),
                ('ipv4_network_mask', models.IntegerField(default=0)),
                ('dns', models.TextField(blank=True)),
                ('archive', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True)),
                ('admin_page_url', models.URLField(blank=True)),
                ('accounts_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='res.resource')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='org.employee')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='org.organization')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='equipment.service')),
                ('resource_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='res.resourcetype')),
            ],
            options={
                'verbose_name': 'Resource',
            },
        ),
    ]
