# Generated by Django 5.0.3 on 2024-06-17 07:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceGroup',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=9)),
                ('delete_mark', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='res.resource')),
            ],
            options={
                'verbose_name': 'Resource Group',
            },
        ),
    ]
