# Generated by Django 5.0.3 on 2024-05-15 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'verbose_name': 'Resource'},
        ),
    ]
