# Generated by Django 5.0.3 on 2024-06-18 06:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0002_resourcegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcegroup',
            name='archive',
            field=models.BooleanField(default=False, help_text='Is archived'),
        ),
        migrations.AddField(
            model_name='resourcegroup',
            name='comment',
            field=models.TextField(blank=True, help_text='Comment'),
        ),
        migrations.AddField(
            model_name='resourcegroup',
            name='create_date',
            field=models.DateField(default=datetime.date.today, help_text='Create date', null=True),
        ),
        migrations.AddField(
            model_name='resourcegroup',
            name='technical',
            field=models.BooleanField(default=False, help_text='Technical group'),
        ),
        migrations.AddField(
            model_name='resourcegroup',
            name='title',
            field=models.CharField(blank=True, help_text='Full title', max_length=150),
        ),
        migrations.AlterField(
            model_name='resourcegroup',
            name='name',
            field=models.CharField(blank=True, help_text='Name', max_length=150),
        ),
        migrations.AlterField(
            model_name='resourcegroup',
            name='resource',
            field=models.ForeignKey(help_text='Resource', on_delete=django.db.models.deletion.CASCADE, to='res.resource'),
        ),
    ]
