# Generated by Django 5.0.3 on 2024-05-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0003_alter_resource_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
