# Generated by Django 5.0.4 on 2024-05-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0006_resourcecategory_resourcetype_resource_resource_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcetype',
            name='category',
        ),
        migrations.RemoveField(
            model_name='resourcecategory',
            name='guid',
        ),
        migrations.AlterField(
            model_name='resourcecategory',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
