# Generated by Django 5.0.3 on 2025-06-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0007_alter_resource_resource_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='cached_full_path_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
