# Generated by Django 5.0.4 on 2024-05-16 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0007_remove_resourcecategory_guid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcetype',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='types', to='res.resourcecategory'),
            preserve_default=False,
        ),
    ]
