# Generated by Django 5.0.3 on 2024-05-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0008_resourcetype_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='admin_page_url',
            field=models.URLField(blank=True),
        ),
    ]
