# Generated by Django 5.0.4 on 2025-07-03 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0008_resource_cached_full_path_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='modified_time',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AddField(
            model_name='resourcegroup',
            name='modified_time',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AddField(
            model_name='resourcetype',
            name='modified_time',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
