# Generated by Django 5.0.4 on 2024-05-22 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0009_resource_admin_page_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='resource_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='res.resourcecategory'),
        ),
    ]
