# Generated by Django 5.0.4 on 2024-05-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0010_resource_resource_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_category',
            field=models.CharField(blank=True, choices=[('acc', 'Учетная запись'), ('remote', 'Сетевой'), ('local', 'Локальный'), ('technical', 'Технологический'), ('network', 'Подсеть'), ('system', 'Информационная система'), ('routing', 'Маршрутизация'), ('management', 'Управление и мониторинг')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resourcetype',
            name='category',
            field=models.CharField(blank=True, choices=[('acc', 'Учетная запись'), ('remote', 'Сетевой'), ('local', 'Локальный'), ('technical', 'Технологический'), ('network', 'Подсеть'), ('system', 'Информационная система'), ('routing', 'Маршрутизация'), ('management', 'Управление и мониторинг')], max_length=20),
        ),
        migrations.DeleteModel(
            name='ResourceCategory',
        ),
    ]
