# Generated by Django 5.0.4 on 2024-05-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0011_alter_resource_resource_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_category',
            field=models.CharField(blank=True, choices=[('accounts', 'Accounts'), ('remote', 'Remote resource'), ('local', 'Local'), ('technical', 'Technical'), ('network', 'Sub network'), ('system', 'Information system'), ('routing', 'Routing'), ('management', 'Management and monitoring')], max_length=20),
        ),
        migrations.AlterField(
            model_name='resourcetype',
            name='category',
            field=models.CharField(blank=True, choices=[('accounts', 'Accounts'), ('remote', 'Remote resource'), ('local', 'Local'), ('technical', 'Technical'), ('network', 'Sub network'), ('system', 'Information system'), ('routing', 'Routing'), ('management', 'Management and monitoring')], max_length=20),
        ),
    ]
