# Generated by Django 5.0.4 on 2025-07-29 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0016_alter_resource_created_alter_resourcegroup_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 29, 21, 54, 50, 829559), editable=False),
        ),
        migrations.AlterField(
            model_name='resourcegroup',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 29, 21, 54, 50, 829559), editable=False),
        ),
        migrations.AlterField(
            model_name='resourcetype',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 29, 21, 54, 50, 829559), editable=False),
        ),
    ]
