# Generated by Django 5.0.3 on 2025-08-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0027_alter_resource_created_alter_resourcegroup_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='resourcegroup',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='resourcetype',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
