# Generated by Django 4.2.23 on 2025-08-31 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0028_alter_resource_created_alter_resourcegroup_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='res.resourcetype'),
        ),
    ]
