# Generated by Django 5.2.7 on 2025-10-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0031_alter_resource_delete_mark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcetype',
            name='category',
            field=models.CharField(choices=[('accounts', 'Accounts'), ('remote', 'Remote resource'), ('local', 'Local'), ('technical', 'Technical'), ('network', 'Sub network'), ('system', 'Information system'), ('routing', 'Routing'), ('management', 'Management and monitoring')], max_length=20),
        ),
    ]
