# Generated by Django 5.0.4 on 2024-06-05 19:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtSystem',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('enabled', models.BooleanField(default=True)),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
            ],
            options={
                'verbose_name': 'External System',
            },
        ),
    ]
