# Generated by Django 5.0.4 on 2025-08-22 04:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_alter_extsystem_created_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extsystem',
            name='created_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 22, 4, 22, 42, 50080, tzinfo=datetime.timezone.utc)),
        ),
    ]
