# Generated by Django 5.0.4 on 2025-08-22 04:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_alter_extsystem_created_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extsystem',
            name='created_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
